---
title: 'Dados Abertos Governamentais: Repositórios e Contribuidores'
author: "Lorena Pereira"
date: "January 31, 2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
library(networkD3)
library(here)

```

## Pessoas contribuidoras nos repositórios
```{r message = FALSE}

contributors_file <- read_csv("../../data/contributors_edu.csv")

glimpse(contributors_file)
```

## Filtrando os repositórios com contribuição por mais de uma pessoa
```{r}

ids <- contributors_file %>% 
  group_by(repo_id, repo_name) %>% 
  summarise(count = n()) %>%
  filter(count > 1) %>%
  select(repo_id)

ids <- c(ids$repo_id)

contributors_file <- contributors_file %>% filter(repo_id %in% ids)

```

## Montando os nós
```{r}

repositories <- contributors_file %>% 
  select(repo_id, repo_name) %>% 
  group_by(repo_id, repo_name) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>%
  mutate(type = 'repo') %>%
  select(id = repo_id, name = repo_name, count, type)

contributors <- contributors_file %>% 
  select(contributor_id, contributor_login) %>% 
  group_by(contributor_id, contributor_login) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>%
  mutate(type = 'user') %>% 
  select(id = contributor_id, name = contributor_login, count, type)

nodes <- rbind(repositories, contributors)

nodes <- rowid_to_column(nodes, "index") %>% 
  mutate(index = index -1)

```

## Montando os links
```{r}

links <- contributors_file %>% 
          mutate(value = 1, source = contributor_id, target = repo_id) %>% 
          select(source, target, value)

temp <- inner_join(links, nodes, by=c('source'='id')) %>%
        mutate(source_index = index)

temp <- inner_join(temp, nodes, by=c('target'='id')) %>%
        mutate(target_index = index.y)

links <- temp %>% 
  mutate(source = source_index, target = target_index, value) %>%
  select(source, target, value)

```

## Gerando rede de contribuições

```{r message = FALSE}

network <- forceNetwork(Links = links, Nodes = nodes,
            Source = "source", Target = "target",
            Value = "value", NodeID = "name",
            Group = "type", opacity = 0.8, 
            fontSize = 24, charge=-7, zoom = T,
            colourScale = JS('d3.scaleOrdinal().domain(["repo", "user"]).range(["#FE4A31", "#2D2E2C"])')
)

saveNetwork(network, 'network_edu.html')

network
```

## Qual a frequência de contribuintes?
```{r message = FALSE}

repositories %>% 
  select(numero_contribuintes = count) %>% 
  group_by(numero_contribuintes) %>% 
  summarise(frequencia = n())

```

#### Por hora
